## Fudamentos

#### Python como Calculadora

In [2]:
# Addition, subtraction
print(5 + 3)
print(5 - 2)

# Multiplication, division, modulo, and exponentiation
print(3 * 4)
print(10 / 3)
print(18 % 3)
print(4 ** 3)

# Calculate two to the power of five
print(2**5)

8
3
12
3.3333333333333335
0
64
32


## Variáveis

inteiro - int
flutuante - float
string - str
booleano - bool

In [4]:
altura = 1.79
peso = 76

In [6]:
imc = peso / altura ** 2
print(imc)

23.719609250647608


In [7]:
type(imc)

float

Tipos de variáveis

In [8]:
'ab' + 'cd'

'abcd'

In [9]:
soma = 2 + 3

In [10]:
type(soma)

int

In [12]:
savings = 100
new_savings = 40

# Calculate total_savings using savings and new_savings
total_savings = savings + new_savings
print(total_savings)

# Print the type of total_savings
print(type(total_savings))

140
<class 'int'>


In [13]:
intro = "Hello! How are you?"

# Assign sum of intro and intro to doubleintro
doubleintro = intro + intro

# Print out doubleintro
print(doubleintro)

Hello! How are you?Hello! How are you?


## Listas

In [14]:
lista_teste = ['a', 'b', 'c']

In [15]:
lista_teste

['a', 'b', 'c']

In [17]:
#Lista com números e strings
mix = ['a', 'b', 44, 1.75]
mix

['a', 'b', 44, 1.75]

In [20]:
# Lista de listas
pessoas = [['Liz', 1.75], ['Emma', 1.68], ['Dad', 1.98]]
pessoas

[['Liz', 1.75], ['Emma', 1.68], ['Dad', 1.98]]

In [21]:
type(pessoas)

list

In [22]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Create list areas
areas = [hall, kit, liv, bed, bath]

# Print areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5]


In [23]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv],
         ["bedroom", bed],
         ["bathroom", bath]]
        


# Print out house
print(house)

# Print out the type of house
print(type(house))


[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


#### Subconjunto de listas

In [24]:
mix[2]

44

In [25]:
mix[-1]

1.75

Slicing

In [27]:
mix[2:4]

[44, 1.75]

In [29]:
mix[:3]

['a', 'b', 44]

In [ ]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1])

# Print out last element from areas
print(areas[-1])

# Print out the area of the living room
print(areas[5])

In [ ]:
house = [["hallway", 11.25],
         ["kitchen", 18.0],
         ["living room", 20.0],
         ["bedroom", 10.75],
         ["bathroom", 9.50]]

# Subset the house list
house[-1][1]

## Manipulando Listas

In [31]:
nova_lista = [1, 2, 3, 4, 5, 6, 7]
nova_lista


[1, 2, 3, 4, 5, 6, 7]

In [32]:
nova_lista[3] = 44
nova_lista

[1, 2, 3, 44, 5, 6, 7]

#### Adicionando e removendo elementos

In [33]:
x = ['a', 'b', 'c']
y = x
y[1] = 'z'
y

['a', 'z', 'c']

In [35]:
x = ['a', 'b', 'c']
y = list(x)
y = x[:]
y[1] = 'z'
x

['a', 'b', 'c']

## Funções

built-in functions

In [36]:
# Create variables var1 and var2
var1 = [1, 2, 3, 4]
var2 = True

# Print out type of var1
print(type(var1))

# Print out length of var1
print(len(var1))

# Convert var2 to an integer: out2
out2 = int(var2)

<class 'list'>
4


In [37]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)

# Print out full_sorted
print(full_sorted)

[20.0, 18.0, 11.25, 10.75, 9.5]


#### Métodos

In [38]:
var = [1, 2, 3, 4]

In [39]:
var.index(1)

0

In [40]:
var.count(2)

1

In [41]:
## str métodos
irma = 'liz'
irma.capitalize()

'Liz'

Tudo em python é objeto. Cada objeto tem seus métodos associados, dependendo do tipo.

In [42]:
irma.replace('z', 'sa')

'lisa'

In [43]:
# string to experiment with: place
place = "poolhouse"

# Use upper() on place: place_up
place_up = place.upper()

# Print out place and place_up
print(place)
print(place_up)

# Print out the number of o's in place
print(place.count("o"))

poolhouse
POOLHOUSE
3


In [44]:
# Create list areas
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Use append twice to add poolhouse and garage size
areas.append(24.5)
areas.append(15.45)

# Print out areas
print(areas)

# Reverse the orders of the elements in areas
areas.reverse()

# Print out areas
print(areas)

[11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]
[15.45, 24.5, 9.5, 10.75, 20.0, 18.0, 11.25]


### Pacotes

O que são pacotes?
Exemplos: Pandas, Numpy, Matplotlib

import numpy as np

np.array([1, 2, 3])

In [45]:
# Definition of radius
r = 0.43

# Import the math package
import math

# Calculate C
C = 2 * r * math.pi

# Calculate A
A = math.pi * r ** 2

# Build printout
print("Circumference: " + str(C))
print("Area: " + str(A))

Circumference: 2.701769682087222
Area: 0.5808804816487527


In [46]:
# Definition of radius
r = 192500

# Import radians function of math package
from math import radians

# Travel distance of Moon over 12 degrees. Store in dist.
phi = radians(12)
dist = r*phi

# Print out dist
print (dist)

40317.10572106901


## NumPy

Por que usar Numeric Python?

Array, o que são:

In [49]:
pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 4.4 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [51]:
import numpy as np
altura = [1.73, 1.68, 1.71, 1.89, 1.79]
peso = [65.4, 59.2, 63.6, 88.4, 68.7]

np_altura = np.array(altura)
np_peso = np.array(peso)

In [53]:
np_altura

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [54]:
np_peso

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [59]:
imc = np_peso / np_altura ** 2
imc

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [60]:
#Existe uma diferença:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [61]:
#imprimindo a lista normal
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [62]:
#imprimindo a array
numpy_array + numpy_array

array([2, 4, 6])

In [63]:
#acessando o índice numa array
imc > 21

array([ True, False,  True,  True,  True])

In [64]:
#ou acessando o elemento interno que seja maior que 23:
imc[imc > 23]

array([24.7473475])

In [65]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Import the numpy package as np
import numpy as np

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


### 2D Numpy Arrays

In [66]:
#cada sublista corresponde a uma 1D da array
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], [65.4, 59.2, 63.6, 88.4, 68.7]])

np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [67]:
np_2d.shape

(2, 5)

In [68]:
np_2d[0][2]

np.float64(1.71)

In [69]:
np_2d[0, 2]

np.float64(1.71)

In [71]:
#Selecionando, os elementos das duas linhas, mas do 1 e 2 
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [72]:
#seleciomando os elementos da segunda linha, e todas as colunas
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [73]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Import numpy
import numpy as np

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


Estatíscia básica com Numpy

np.mean(np_city[:, 0])
np.median()

sum(), sort()...

In [76]:
# Import numpy
import numpy as np

baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

np_baseball = np.array(baseball)

# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: " + str(corr))

Average: 198.25
Median: 199.0
Standard Deviation: 14.635146053251399
Correlation: [[1.         0.95865738]
 [0.95865738 1.        ]]
